### ISSUE TITLE
Replying large files

### ISSUE THREAD

**Issue by skerit** [c4milo/fusejs#34]
I see you need to reply to `read` methods with a buffer containing all the data, won't that fail for files that are over 1.7GiB?

**Comment by thejinx0r** [comment]
No it won't fail because the kernel never requests to read files that large at once.
The kernel will only request a small piece of that file to be read. 
Once that chunk of file is read, the kernel will request another chunk. 
At somepoint, the v8 garbage collector will kick in and clear out the unused buffers.

So, there shouldn't be a problem with this.
If there is, it's most likely at the user implementation level.

**Comment by skerit** [comment]
Oh, that's great.
Had no idea that's how it worked, but it makes sense of course.
Thanks for the response.
